# @package _global_

defaults:
  - _self_
  - data: acouslic_sample
  - model: acouslic
  - logger: null
  - callbacks: default
  - trainer: default
  - paths: default
  - extras: default
  - hydra: default

task_name: "eval"

tags: ["dev", "acouslic"]

# passing checkpoint path is necessary for evaluation
ckpt_path: ""
